export const APP_LABELS = {
  common: {
    loading: "Memuat data...",
    errorGeneric: "Data tidak dapat dimuat saat ini. Silakan coba kembali beberapa saat lagi.",
    close: "Tutup",
    cancel: "Batal",
    save: "Simpan",
    add: "Tambah",
    search: "Cari",
    apply: "Terapkan",
    exportExcel: "Ekspor Excel",
    printPDF: "Cetak PDF",
    back: "Sebelumnya",
    next: "Selanjutnya",
    view: "Lihat",
    download: "Unduh",
    copyLink: "Salin Link",
    openInGDrive: "Buka di Google Drive",
    all: "Semua",
    systemActive: "Sistem Aktif",
    explore: "Eksplor",
    folder: "Folder",
    open: "Buka",
    processing: "Memproses...",
    saving: "Menyimpan...",
    uploading: "Mengunggah...",
    file: "Berkas",
    document: "Dokumen",
    noEmail: "Tidak ada email",
    drive: "Drive",
    empty: "Kosong",
    item: "Item",
  },
  sidebar: {
    groups: {
      menu: "Menu",
      archiveManagement: "Manajemen Arsip",
      project: "Pekerjaan",
      employee: "Karyawan",
      hrm: "HRM",
      legal: "Dashboard Legal",
      admin: "Admin",
      alat: "Alat",
    },
    items: {
      dashboard: "Dashboard Utama",
      calendar: "Kalender",
      tasks: "Daftar Potensi Klien",
      berkas: "Berkas",
      dokumentasi: "Dokumentasi",
      pengumuman: "Pengumuman",
      arsipDokumen: "Arsip",
      laporanOperasional: "Laporan Operasional",
      retainer: "Retainer",
      perorangan: "Non Retainer",
      daftarKaryawan: "Daftar Karyawan",
      skalaPrioritas: "Skala Prioritas",
      suratInternal: "Surat Internal",
      dashboardHrm: "Dashboard HRM",
      daftarRetainer: "Daftar Retainer",
      dataPelamar: "Data Pelamar",
      dokumenPelamar: "Dokumen Pelamar",
      dashboardLegal: "Dashboard Legal",
      documentAutomation: "Otomatisasi Dokumen",
      createLetter: "Buat Surat",
      templateManagement: "Manajemen Templat",
      contractManagement: "Manajemen Kontrak",
      allContracts: "Semua Kontrak",
      expiryMonitoring: "Pemantauan Kedaluwarsa",
      employeeLegal: "Legal Karyawan",
      approvals: "Alur Persetujuan",
      archiveLegal: "Arsip Hukum",
      compliance: "Kepatuhan",
      legalRequests: "Permintaan Legal",
      reports: "Laporan",
      settings: "Pengaturan",
      accessManagement: "Manajemen Akses",
      // Tools / Alat items
      imageTools: "Image",
      pdfTools: "PDF",
      wordTools: "Word",
      excelTools: "Excel",
      bgEraser: "Background Eraser",
      imageCrop: "Image Crop",
      imageFilter: "Image Color Filter",
      pdfToImage: "PDF To Image",
      pdfToWord: "PDF To Word",
      pdfCompress: "PDF Compress",
      pdfCombine: "PDF Combine",
      pdfSlice: "PDF Slice",
      pdfSensor: "PDF Sensor",
      pdfTtd: "PDF TTD",
      docGenerator: "Document Template Generator",
      excelPdf: "Excel PDF Rapi",
    }
  },
  header: {
    titles: {
      dashboard: "Dashboard",
      calendar: "Kalender",
      berkas: "Berkas",
      dokumentasi: "Dokumentasi",
      pengumuman: "Pengumuman",
      retainer: "Retainer",
      perorangan: "Non Retainer",
      daftarKaryawan: "Daftar Karyawan",
      skalaPrioritas: "Skala Prioritas",
      suratInternal: "Surat Internal",
      laporanOperasional: "Laporan Operasional",
      dashboardHrm: "Dashboard HRM",
      dataPelamar: "Data Pelamar",
      dokumenPelamar: "Dokumen Pelamar",
      daftarRetainerHrm: "Daftar Retainer",
      default: "Sistem Manajemen",
    }
  },
  dashboard: {
    title: "Papan Informasi",
    welcome: "Selamat Datang,",
    welcomeSub: "Berikut Ringkasan kegiatan hari ini",
    cards: {
      activeProjects: "Pekerjaan Aktif",
      priorityTasks: "Tugas Prioritas",
      archiveFolder: "Folder Utama Arsip",
      teamMembers: "Anggota Tim",
    },
    sections: {
      agenda: "Agenda & Deadline Terdekat",
      quickAccess: "Akses Cepat",
      upcomingDeadlines: "Tenggat Waktu Mendekat",
      activityLogs: "Aktivitas Terbaru",
      announcements: "Pengumuman Internal",
      recentDocs: "Dokumen Terbaru",
    },
    quickActions: {
      createNote: "Buat Catatan",
      addProject: "Tambah Pekerjaan",
      uploadArchive: "Upload Arsip",
      addData: "Tambah Data",
    },
    empty: {
      agenda: "Tidak ada agenda hukum untuk tanggal ini.",
      deadlines: "Tidak ada tenggat waktu kontrak mendesak.",
      activityLogs: "Belum ada catatan aktivitas.",
      announcements: "Tidak ada pengumuman baru.",
      recentDocs: "Tidak ada dokumen di folder utama.",
    },
    alerts: {
      adminOnlyLogs: "Log aktivitas sistem terenkripsi dan hanya dapat diakses oleh Administrator.",
      seeAll: "Lihat Semua",
      resetFilter: "Reset Filter",
    }
  },
  laporanOperasional: {
    summary: {
      retainer: "Pekerjaan Retainer",
      nonRetainer: "Pekerjaan Non-Retainer",
      internal: "Pekerjaan Internal",
      laporanBerkala: "Lainnya",
    },
    printHeader: "Laporan Operasional Kantor Hukum Narasumber Hukum",
    printSubtext: "Jenis Data: ",
    printSubtextDate: " | Tanggal Cetak: ",
    tabs: {
      retainer: "Skala Prioritas Retainer",
      nonRetainer: "Non-Retainer",
      internal: "Pekerjaan Internal",
      laporanBerkala: "Lainnya",
    },
    searchPlaceholder: "Cari tugas, deskripsi, klien...",
    filters: {
      allStatus: "-- Semua Status --",
      allQuadrants: "-- Semua Kuadran --",
      completed: "Selesai",
      active: "Aktif",
      pending: "Tertunda",
      q1: "Q1",
      q1Label: "Q1 (Penting & Mendesak)",
      q2: "Q2",
      q2Label: "Q2 (Penting tapi Tidak Mendesak)",
      q3: "Q3",
      q3Label: "Q3 (Lainnya)",
    },
    table: {
      no: "No",
      tanggal: "Tanggal",
      klien: "Klien/Perusahaan",
      kuadran: "Kuadran",
      kategori: "Kategori",
      deskripsi: "Deskripsi Pekerjaan",
      tugas: "Tugas / Rincian",
      area: "Area",
      status: "Status",
      keterangan: "Keterangan",
      pic: "Penanggung Jawab",
    },
    alerts: {
      noData: "Tidak ada data yang ditemukan.",
      noExportData: "Tidak ada data untuk diekspor.",
      exportSuccess: "Data berhasil diekspor.",
      exportFailed: "Gagal mengekspor data ke Excel.",
    }
  },
  narasumberHukum: {
    title: "Manajemen Arsip",
    subtitle: "Dokumentasi berkas hukum, legal opinion, somasi, dan surat kontrak diatur secara dinamis per perusahaan.",
    searchPlaceholder: "Cari Folder atau Dokumen...",
    createFolderBtn: "+ Buat Folder",
    uploadFileBtn: "+ Unggah Berkas",
    folderNav: "Navigasi Folder",
    drive: "DRIVE",
    archiveMain: "Arsip Utama",
    rootDrive: "Root Drive",
    narasumberHukumUpper: "NARASUMBER HUKUM",
    table: {
      name: "Nama",
      pt: "PT Asosiasi",
      pic: "Akses PIC",
      size: "Ukuran",
      uploadDate: "Diunggah",
      modifiedDate: "Terakhir Diubah",
      owner: "Pemilik",
      actions: "Aksi",
      public: "Publik",
      restricted: "Dibatasi",
    },
    actions: {
      view: "Lihat",
      download: "Unduh",
      copyLink: "Salin Link",
      openInGDrive: "Buka di Google Drive",
      edit: "Edit",
      delete: "Hapus",
      open: "Buka",
      saveName: "Simpan Nama",
      gdriveShort: "G-Drive",
    },
    empty: {
      files: "Belum ada berkas atau subfolder di sini. Gunakan tombol diatas untuk mengisi.",
      recent: "Belum ada dokumen terbaru.",
      noDescription: "Tidak ada keterangan.",
      noPt: "Tidak terikat PT.",
    },
    modals: {
      createFolderTitle: "Buat Subfolder Baru",
      editFolderTitle: "Ubah Nama Folder",
      uploadFileTitle: "Unggah Berkas Baru ke Google Drive",
      folderNameLabel: "Nama Folder",
      folderNamePlaceholder: "Contoh: Legal Opinion PT A",
      newFolderNameLabel: "Nama Folder Baru",
      newFolderNamePlaceholder: "Masukkan nama folder baru...",
      selectFilesLabel: "Pilih Berkas (Multi-upload didukung)",
      customNameLabel: "Nama Berkas Kustom (Opsional)",
      customNamePlaceholder: "Kosongkan untuk menggunakan nama asli file",
      descriptionLabel: "Keterangan / Ringkasan",
      descriptionPlaceholder: "Deskripsi singkat mengenai isi dokumen",
      ptLabel: "PT / Klien Asosiasi (Opsional)",
      ptPlaceholder: "-- Pilih PT Asosiasi --",
      picLabel: "Pilih PIC Keamanan Akses (Opsional)",
      picPlaceholderPublic: "Bersifat publik (dapat dilihat oleh Staf Legal dan Admin)",
      editFileTitle: "Ubah Berkas Hukum & Akses Keamanan",
      fileNameLabel: "Nama Berkas",
      newFileNamePlaceholder: "Masukkan nama berkas baru...",
      closePicMenu: "Tutup Menu PIC",
      selectPicEmployee: "Pilih Karyawan PIC...",
      searchEmployeePlaceholder: "Cari karyawan...",
      noEmployeeFound: "Tidak ada karyawan ditemukan",
      picAccessNote: "* Jika dibatasi, hanya karyawan terpilih dan Administrator yang memiliki hak akses untuk membuka berkas ini.",
      picAccessNoteEdit: "* Perubahan hak akses keamanan PIC akan langsung aktif untuk semua staf setelah disimpan.",
      uploadFileSubmit: "Unggah Berkas",
      saveFileSubmit: "Simpan Berkas",
      createFolderSubmit: "Buat Folder",
      detailFileTitle: "Rincian Berkas Hukum",
      formatLabel: "Format",
      sizeLabel: "Ukuran",
      associatedPtLabel: "PT Klien Asosiasi",
      picAccessLabel: "Hak Akses PIC",
      publicAccessLabel: "Publik (Semua Staf)",
      previewFileTitle: "Pratinjau Berkas",
      previewNotSupportedNote: "Ekstensi/Jenis file ini memerlukan aplikasi eksternal untuk dibuka secara interaktif. Berikut rincian metadatanya:",
      fileTypeLabel: "Jenis Berkas",
      createdDateLabel: "Dibuat Pada",
    },
    alerts: {
      gdriveConnectFailed: "Sistem gagal terhubung ke Google Drive. Pastikan konfigurasi jaringan atau izin akses Anda telah aktif.",
      clipboardSuccess: "Tautan berhasil disalin ke papan klip!",
      createFolderFailed: "Gagal membuat folder baru.",
      uploadFailed: "Gagal mengunggah berkas.",
      deleteFolderConfirm: "Apakah Anda yakin ingin menghapus folder ini beserta seluruh isinya secara permanen dari Google Drive?",
      deleteFolderFailed: "Gagal menghapus folder.",
      deleteFileConfirm: "Apakah Anda yakin ingin menghapus berkas ini secara permanen dari database dan Google Drive?",
      deleteFileFailed: "Gagal menghapus berkas.",
      editFolderFailed: "Gagal mengubah nama folder.",
      editFileFailed: "Gagal mengubah berkas.",
    }
  }
} as const;
